"""empty message

Revision ID: ecb37faccae7
Revises: 67ebf3d6a26b
Create Date: 2021-02-23 17:47:55.376183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb37faccae7'
down_revision = '67ebf3d6a26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('done', table_name='todo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('done', 'todo', ['done'], unique=True)
    # ### end Alembic commands ###
